version: "3.5"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "kwetter"
      MYSQL_USER: "fontys"
      MYSQL_PASSWORD: "fontys"
    volumes:
      - kwetter-mysql:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
volumes:
  kwetter-mysql:
