version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "kwetter"
      MYSQL_USER: "fontys"
      MYSQL_PASSWORD: "fontys"
    volumes:
      - kwetter-mysql:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  kwetter-mysql:
