version: "3.5"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "kwetter"
      MYSQL_USER: "fontys"
      MYSQL_PASSWORD: "fontys"
    volumes:
      - kwetter-mysql:/var/lib/mysql
  kwetter:
    image: kwetter
    depends_on:
      - mysql
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 4848
        published: 4848
        protocol: tcp
        mode: host
volumes:
  kwetter-mysql:
